apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfscontrol
    server: 192.168.1.51
  persistentVolumeReclaimPolicy: Retain
