---
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: redis-storage
        mountPath: /usr/share/nginx/html
    volumes:
    - name: nfs-pv
